version: '3.6'

services:
  api:
    build: .
    container_name: todo-api
    image: todo-api
    ports:
      - "8080:8080"
    networks:
      - overlay
    environment:
      - NODE_ENV=${NODE_ENV}

networks:
  overlay:
